spring.application.name=virtualtryon
spring.datasource.url=jdbc:postgresql://localhost:5432/virtualtryon
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.session.jdbc.initialize-schema=always

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=krups0628@gmail.com
spring.mail.password=lawhxpdxjdpbeojq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.show-sql=true

# WearFashion AI integration
wearfashion.python.base-url=http://127.0.0.1:8000
wearfashion.python.timeout-ms=7200000
wearfashion.generation.async=true
wearfashion.gpu.base-url=https://mutt-udder-easter.ngrok-free.dev
colab.api.url=https://mutt-udder-easter.ngrok-free.dev/tryon